Repository GSG-G9/beauty-salon, pull requests merged in 2021-03, with the labels that each got.

#45 created file structure
  .gitignore
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App/App.js
  client/src/assets/.gitkeep
  client/src/component/index.js
  client/src/index.css
  client/src/index.js
  client/src/pages/index.js
  client/src/utils/index.js
  package-lock.json
  package.json
  server/app.js
  server/controller/admin/index.js
  server/controller/common/index.js
  server/controller/error/index.js
  server/controller/index.js
  server/controller/user/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/index.js
  server/middleware/index.js
  server/routes/index.js
  server/utilis/index.js
Labels: setup

#46 setup eslint in server
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  __test__/test.js
  package-lock.json
  package.json
Labels: awaiting review, back-end, setup

#48 database setup
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
Labels: awaiting review, back-end, setup

#54 Setup travis
  .travis.yml
Labels: awaiting review, setup

#51 install pre-commit
  client/package.json
  package-lock.json
  package.json
Labels: awaiting review, setup

#52 react router-dom setup
  .vscode/settings.json
  client/package.json
  client/src/App/App.js
  client/src/pages/Blogs/index.js
  client/src/pages/Blogs/style.js
  client/src/pages/Book/index.js
  client/src/pages/Book/style.js
  client/src/pages/Contacts/index.js
  client/src/pages/Contacts/style.js
  client/src/pages/Dashboard/Dash_appointment/index.js
  client/src/pages/Dashboard/Dash_appointment/style.js
  client/src/pages/Dashboard/index.js
  client/src/pages/Dashboard/style.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
  client/src/pages/NotFound/index.js
  client/src/pages/NotFound/style.js
  client/src/pages/Profile/index.js
  client/src/pages/Profile/style.js
  client/src/pages/Services/index.js
  client/src/pages/Services/style.js
  client/src/pages/Signin/index.js
  client/src/pages/Signin/style.js
  client/src/pages/Signup/index.js
  client/src/pages/Signup/style.js
  client/src/pages/index.js
  client/src/utils/router.constant.js
Labels: awaiting review, front-end, setup

#50 set up material-ui
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App/App.js
  client/src/App/theme.js
  client/src/index.css
Labels: awaiting review, front-end

#57 sign up route
  .vscode/settings.json
  __test__/signUP.test.js
  __test__/test.js
  package.json
  server/app.js
  server/controller/common/index.js
  server/controller/common/signUp.js
  server/controller/error/index.js
  server/controller/index.js
  server/database/queries/checkEmail.js
  server/database/queries/index.js
  server/database/queries/signup.js
  server/routes/common.js
  server/routes/index.js
  server/utilis/boomify.js
  server/utilis/index.js
  server/utilis/jwt.js
  server/utilis/validation/index.js
  server/utilis/validation/signupValidation.js
Labels: awaiting review, back-end, priority-0

#53 services route
  .circleci/config.yml
  __test__/getAllServices.test.js
  client/package.json
  package.json
  server/controller/common/index.js
  server/controller/common/services.js
  server/controller/index.js
  server/database/queries/index.js
  server/database/queries/services.js
  server/routes/common.js
  server/routes/index.js
Labels: awaiting review, back-end

#55 sign in route
  __test__/signin.test.js
  server/controller/common/index.js
  server/controller/common/signUp.js
  server/controller/common/signin.js
  server/controller/index.js
  server/database/queries/checkUserByEmail.js
  server/database/queries/index.js
  server/routes/common.js
  server/routes/index.js
  server/utilis/validation/index.js
  server/utilis/validation/signinValidation.js
Labels: awaiting review, back-end
