Repository GSG-G9/beauty-salon, pull requests merged in 2021-04, with the labels that each got.

#56 contact-us route backend
  .vscode/settings.json
  __test__/contactus.test.js
  __test__/signUP.test.js
  server/app.js
  server/controller/common/contactus.js
  server/controller/common/index.js
  server/controller/index.js
  server/database/config/build.sql
  server/database/queries/contactus.js
  server/database/queries/index.js
  server/middleware/index.js
  server/middleware/isAdmin.js
  server/middleware/isAuth.js
  server/routes/common.js
  server/routes/index.js
  server/utilis/index.js
  server/utilis/validation/contactusValidation.js
  server/utilis/validation/index.js
Labels: awaiting review, back-end

#59 Get/getBlogs Route
  __test__/getBlogs.test.js
  package-lock.json
  server/controller/common/getBlogs.js
  server/controller/common/index.js
  server/controller/index.js
  server/database/queries/getBlogs.js
  server/database/queries/index.js
  server/routes/index.js
Labels: awaiting review, back-end

#63 Delete booking route
  __test__/deleteBookingByUser.test.js
  __test__/logout.test.js
  package-lock.json
  package.json
  server/controller/common/index.js
  server/controller/common/signUp.js
  server/controller/common/signin.js
  server/controller/index.js
  server/controller/user/deleteBooking.js
  server/controller/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/deleteBook.js
  server/database/queries/index.js
  server/middleware/index.js
  server/middleware/isAdmin.js
  server/middleware/isAuth.js
  server/routes/common.js
  server/routes/index.js
  server/routes/user.js
Labels: awaiting review, back-end

#64 POST/add book
  __test__/addBook.test.js
  __test__/deleteBookingByUser.test.js
  server/controller/common/signin.js
  server/controller/index.js
  server/controller/user/addBook.js
  server/controller/user/index.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/user/addBook.js
  server/database/queries/user/checkAvailability.js
  server/database/queries/user/index.js
  server/middleware/isAuth.js
  server/routes/user.js
  server/utilis/validation/addBookingValidation.js
Labels: awaiting review, back-end

#66 GET/ getUser
  __test__/getProfile.test.js
  server/controller/index.js
  server/controller/user/getProfile.js
  server/controller/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/user/getProfile.js
  server/database/queries/user/index.js
  server/middleware/isAuth.js
  server/routes/user.js
Labels: awaiting review, back-end

#70 GET /api/v1/isAuth
  __test__/getAllServices.test.js
  __test__/getBlogs.test.js
  __test__/getBookingsByDate.test.js
  __test__/protectedRoutes.test.js
  __test__/signUP.test.js
  __test__/signin.test.js
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/user/index.js
  server/controller/user/userData.js
  server/database/config/fakeData.sql
  server/database/queries/getUserData.js
  server/database/queries/index.js
  server/routes/index.js
  server/routes/user.js
Labels: awaiting review, back-end

#71 delete booking by admin
  __test__/deleteBookingByAdmin.test..js
  __test__/getIsAuth.test.js
  __test__/protectedRoutes.test.js
  package.json
  server/controller/admin/deleteBooking.js
  server/controller/admin/index.js
  server/controller/common/signin.js
  server/controller/index.js
  server/database/queries/deleteBookingByAdmin.js
  server/database/queries/index.js
  server/middleware/isAuth.js
  server/routes/admin.js
  server/routes/index.js
Labels: awaiting review, back-end

#74 get booking for given user
  __test__/getBookingForUser.test.js
  package-lock.json
  server/controller/index.js
  server/controller/user/getBookingsForGivenUser.js
  server/controller/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/getBookingsByUserId.js
  server/database/queries/index.js
  server/routes/user.js
Labels: awaiting review, back-end

#69 PATCH api/v1/profile
  .vscode/settings.json
  __test__/updateProfile.test.js
  package-lock.json
  server/controller/error/index.js
  server/controller/index.js
  server/controller/user/index.js
  server/controller/user/updateUserController.js
  server/database/config/connection.js
  server/database/queries/index.js
  server/database/queries/updateUserQuery.js
  server/routes/user.js
  server/utilis/index.js
  server/utilis/validation/index.js
  server/utilis/validation/updateUserValidation.js
Labels: awaiting review, back-end

#81 Change font family
  client/public/index.html
  client/src/App/theme.js
  client/src/index.js
Labels: awaiting review, enhancement, front-end

#87 Reset css style
  client/src/App/App.js
Labels: awaiting review, front-end

#73 Button Component
  client/package-lock.json
  client/src/component/Button/index.js
  client/src/component/index.js
Labels: awaiting review, front-end

#84 Loading Component
  client/src/component/Loading/index.js
  client/src/component/Loading/style.js
  client/src/component/index.js
Labels: awaiting review, front-end

#77 Input Date Component
  client/package-lock.json
  client/package.json
  client/src/component/InputDate/index.js
  client/src/component/InputTime/index.js
  client/src/component/index.js
  package-lock.json
Labels: awaiting review, front-end

#78 service card component
  client/src/component/ServiceCard/index.js
  client/src/component/ServiceCard/style.js
  client/src/component/index.js
Labels: awaiting review, front-end

#67 text field component
  client/src/App/App.js
  client/src/component/index.js
  client/src/component/inputText/index.js
  client/src/component/inputText/style.js
Labels: awaiting review, front-end

#85 footer component
  client/package-lock.json
  client/src/assets/images/logo192.png
  client/src/component/footer/index.js
  client/src/component/footer/style.js
  client/src/component/index.js
Labels: awaiting review, front-end

#82 service card component for home page
  client/src/component/index.js
  client/src/component/seviceCardHomePage/index.js
  client/src/component/seviceCardHomePage/style.js
Labels: awaiting review, front-end

#90 Select component
  client/src/App/theme.js
  client/src/component/Select/index.js
  client/src/component/Select/style.js
  client/src/component/index.js
Labels: awaiting review, front-end

#89 fix database schema
  __test__/getAllServices.test.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
Labels: awaiting review, back-end

#94 Blogs Card component
  client/src/component/BlogCard/index.js
  client/src/component/BlogCard/style.js
  client/src/component/index.js
Labels: awaiting review, front-end

#97 Fix Loading component
  client/src/component/Loading/index.js
  client/src/component/Loading/style.js
Labels: awaiting review, front-end

#76 Header Component
  client/.gitignore
  client/src/assets/images/icon.svg
  client/src/component/header/NavMobile.js
  client/src/component/header/index.js
  client/src/component/header/style.js
  client/src/component/index.js
  client/src/pages/Blogs/index.js
  client/src/utils/router.constant.js
Labels: awaiting review, front-end

#102 Fix Input field style
  client/src/component/inputText/style.js
Labels: awaiting review, front-end

#99 user context
  client/package-lock.json
  client/package.json
  client/src/App/App.js
  client/src/component/route/adminRoute.js
  client/src/component/route/guestRoute.js
  client/src/component/route/index.js
  client/src/component/route/userRoute.js
  client/src/utils/router.constant.js
  client/src/utils/userProvider.js
Labels: awaiting review, front-end

#95 signup page
  client/package-lock.json
  client/package.json
  client/src/component/route/userRoute.js
  client/src/pages/Signup/index.js
  client/src/pages/Signup/style.js
  client/src/utils/checkValidationPureFunction.js
  client/src/utils/index.js
  client/src/utils/signUpValidation.js
  server/controller/common/signUp.js
  server/controller/error/index.js
Labels: awaiting review, front-end

#91 signin page
  client/src/pages/Signin/index.js
  client/src/pages/Signin/style.js
  client/src/utils/checkValidationPureFunction.js
  client/src/utils/index.js
  client/src/utils/signinValidation.js
  server/utilis/validation/signinValidation.js
Labels: awaiting review, front-end

#109 Edit components to be controlled by the parent component
  client/src/component/InputDate/index.js
  client/src/component/InputTime/index.js
  client/src/component/Select/index.js
Labels: awaiting review, front-end

#111 Edit addBook controller and addBookingValidation
  __test__/addBook.test.js
  server/controller/user/addBook.js
  server/database/queries/user/addBook.js
  server/utilis/validation/addBookingValidation.js
Labels: awaiting review, back-end

#114 Coming Soon page
  client/src/App/App.js
  client/src/assets/images/black.jpg
  client/src/pages/ComingSoon/index.js
  client/src/pages/ComingSoon/style.js
  client/src/pages/index.js
Labels: awaiting review, front-end

#93 Home Page
  client/src/assets/images/landingBackground.jpg
  client/src/component/BlogCard/index.js
  client/src/component/BlogCard/style.js
  client/src/component/header/style.js
  client/src/component/seviceCardHomePage/style.js
  client/src/pages/Home/index.js
  client/src/pages/Home/style.js
Labels: awaiting review, front-end

#100 profile page
  __test__/getBookingForUser.test.js
  client/src/pages/Profile/Reservations/Table/index.js
  client/src/pages/Profile/Reservations/Table/style.js
  client/src/pages/Profile/Reservations/index.js
  client/src/pages/Profile/Reservations/style.js
  client/src/pages/Profile/SideBar/index.js
  client/src/pages/Profile/SideBar/style.js
  client/src/pages/Profile/SideBar/tabPanel.js
  client/src/pages/Profile/UpdateInfo/index.js
  client/src/pages/Profile/UpdateInfo/style.js
  client/src/pages/Profile/UserInfo/index.js
  client/src/pages/Profile/UserInfo/style.js
  client/src/pages/Profile/index.js
  client/src/pages/Profile/style.js
  client/src/utils/index.js
  client/src/utils/updateUserValidation.js
  server/controller/user/getBookingsForGivenUser.js
  server/controller/user/updateUserController.js
  server/database/queries/getBookingsByUserId.js
Labels: awaiting review, front-end

#106 services Page
  __test__/getAllServices.test.js
  __test__/getBookingsByDate.test.js
  client/src/component/ServiceCard/index.js
  client/src/component/ServiceCard/style.js
  client/src/pages/Services/index.js
  client/src/pages/Services/style.js
  server/database/config/fakeData.sql
Labels: awaiting review, front-end

#117 Build header functionality
  client/src/component/header/NavMobile.js
  client/src/component/header/index.js
  client/src/component/route/userRoute.js
  client/src/pages/Signin/index.js
  client/src/pages/Signup/index.js
  client/src/utils/userProvider.js
Labels: awaiting review, enhancement, front-end

#92 booking page
  client/src/assets/images/Salon+pic+cover 1.svg
  client/src/component/Select/style.js
  client/src/pages/Book/BookingSection/index.js
  client/src/pages/Book/BookingSection/style.js
  client/src/pages/Book/WelcomeSection/index.js
  client/src/pages/Book/WelcomeSection/style.js
  client/src/pages/Book/index.js
  server/database/queries/bookingsQuery.js
Labels: front-end

#116 contact page
  __test__/contactus.test.js
  client/src/assets/images/map.png
  client/src/pages/Contacts/index.js
  client/src/pages/Contacts/style.js
  client/src/utils/contactValidation.js
  client/src/utils/index.js
  server/controller/common/contactus.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/contactus.js
  server/utilis/validation/contactusValidation.js
Labels: change request, front-end

#122 Fix Private routes bugs
  client/src/component/header/index.js
  client/src/component/route/userRoute.js
  client/src/utils/userProvider.js
Labels: awaiting review, bug

#127 fix getBookingByDate test
  __test__/getBookingsByDate.test.js
Labels: awaiting review, bug

#128 Fix getBookingForUser query
  __test__/getBookingForUser.test.js
  server/database/config/fakeData.sql
  server/database/queries/getBookingsByUserId.js
Labels: awaiting review, bug

#135 fix service page
  client/src/pages/Services/style.js
  server/database/config/fakeData.sql
Labels: awaiting review, bug

#131 Fix Footer
  client/src/component/footer/style.js
Labels: awaiting review, bug

#139 fix contact page
  client/src/pages/Contacts/style.js
Labels: awaiting review, bug

#140 add map
  client/package-lock.json
  client/package.json
  client/src/assets/images/map.png
  client/src/component/index.js
  client/src/component/mapComponent/index.js
  client/src/component/mapComponent/style.js
  client/src/pages/Contacts/index.js
  client/src/pages/Contacts/map/index.js
  client/src/pages/Contacts/style.js
Labels: awaiting review, enhancement

#136 fix booking page bugs
  client/src/pages/Book/BookingSection/index.js
  client/src/pages/Book/BookingSection/style.js
  client/src/pages/Book/WelcomeSection/style.js
Labels: awaiting review, bug, enhancement

#146 edit readme file
  README.md
Labels: awaiting review
